name: travelr
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: ^2.0.0 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  swipable_stack: ^0.4.0
  get: ^4.6.6
  uuid: ^4.5.1
  http: ^1.3.0
  web_socket_channel: ^3.0.3
  geolocator: ^14.0.2
  firebase_messaging: ^15.2.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    #- assets/icons/
    #- assets/fonts/

  fonts:              # Required if your app uses custom fonts
      - family: Northlane
        fonts:
          - asset: assets/fonts/northlane_two.OTF