// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxN51Pvcw275VbXBL4xV-ReWuBo-SqZwg',
    appId: '1:837109274820:web:67513a9e7c7df0e9351191',
    messagingSenderId: '837109274820',
    projectId: 'trave-14bee',
    authDomain: 'trave-14bee.firebaseapp.com',
    storageBucket: 'trave-14bee.firebasestorage.app',
    measurementId: 'G-LEF4QDFGDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6XbhgXvJJSK_IeEfDJyeOjeGOjQ4K5Gk',
    appId: '1:837109274820:android:1463f88d81eef9ab351191',
    messagingSenderId: '837109274820',
    projectId: 'trave-14bee',
    storageBucket: 'trave-14bee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOzgZvZGPpxoG57fgWou45JpzOUv12Y2E',
    appId: '1:837109274820:ios:e4651f14ca5fceae351191',
    messagingSenderId: '837109274820',
    projectId: 'trave-14bee',
    storageBucket: 'trave-14bee.firebasestorage.app',
    iosBundleId: 'com.example.travelr',
  );
}
